### ISSUE TITLE
API 요청 코드 작성

### ISSUE THREAD

**Issue by publdaze** [KEEPER31337/Game-Baseball#20]
## 📝 Description
- [API 문서](http://dev.keeper.or.kr:81/docs/game/baseball.html)에 올라온 API 요청 코드 작성

## ✅ TODO

- [x] api 폴더 생성 및 dto 폴더 생성 - 구조 잡기
- [x]  dto 코드 작성
- [x] [플레이 했는지 확인하기](http://dev.keeper.or.kr:81/docs/game/baseball.html#_플레이_했는지_확인하기)
- [x] [야구게임 START](http://dev.keeper.or.kr:81/docs/game/baseball.html#_야구_게임_start)
- [x] [야구게임 GUESS](http://dev.keeper.or.kr:81/docs/game/baseball.html#_야구_게임_guess)
- [x] [야구게임 결과 가져오기](http://dev.keeper.or.kr:81/docs/game/baseball.html#_야구_게임_결과_가져오기)
