### ISSUE TITLE
게임 화면 구조 잡기

### ISSUE THREAD

**Issue by publdaze** [KEEPER31337/Game-Baseball#8]
## 📝 Description
<img width="200" alt="image" src="https://github.com/KEEPER31337/Game-Baseball/assets/78250089/d0ee53eb-e180-4264-a118-cf6446dcb36e"> <img width="200" alt="image" src="https://github.com/KEEPER31337/Game-Baseball/assets/78250089/9b80074b-1313-49bb-8039-faf042551c55">

게임 화면에 들어갈 요소(컴포넌트) 배치하기

```
if 게임 시작 전 return <게임 시작 화면 컴포넌트 />
else {
  return (
    <획득 가능 포인트 섹션 />
    <카운트 다운 progress bar 섹션 />
    <회차 정보 섹션 />
    <숫자 입력 섹션 />  <타자 버튼 />
  )
}
```

## ✅ TODO

- [x] 각 컴포넌트 파일 생성
- [x] 컴포넌트 import 해서 배치하기
- [ ] 버튼 아이콘 받아와서 배치하기 -> #11 
- [x] 내부 아이템 중앙 정렬
